# Generated by Django 4.2.2 on 2023-06-24 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BernardoLegal', max_length=100)),
                ('current_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_altitude', models.DecimalField(decimal_places=3, max_digits=9)),
                ('current_speed', models.DecimalField(decimal_places=3, max_digits=9)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_app.gpsdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('final_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_app.gpsdevice')),
                ('first_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_app.previouslocation')),
            ],
        ),
    ]
