# Generated by Django 4.2.2 on 2023-07-04 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='cercado',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=9), size=2), default=1, size=4),
            preserve_default=False,
        ),
    ]
