# Generated by Django 4.2.2 on 2023-07-04 11:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0002_gpsdevice_cercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdevice',
            name='cercado',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=9), size=2), null=True, size=4),
        ),
    ]
