# Generated by Django 4.2.2 on 2023-07-04 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0004_alter_gpsdevice_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='previouslocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 11, 58, 0, 540448, tzinfo=datetime.timezone.utc)),
        ),
    ]
