# Generated by Django 4.2.2 on 2023-07-04 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0005_remove_gpsdevice_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='cercado',
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='previouslocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
