# Generated by Django 4.2.2 on 2023-06-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0005_alter_gpsdevice_id_alter_movement_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='user_id',
        ),
    ]
