# Generated by Django 4.2.2 on 2023-07-04 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0006_remove_gpsdevice_cercado_gpsdevice_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='cercado',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=9), size=2), null=True, size=4),
        ),
    ]
