# Generated by Django 4.2.2 on 2023-06-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0007_pastlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='timestamp',
        ),
    ]
