# Generated by Django 4.2.2 on 2023-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0008_cercado_alter_gpsdevice_cercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cercado',
            name='name',
            field=models.CharField(default='Nameless Cercado', max_length=100),
        ),
        migrations.AlterField(
            model_name='gpsdevice',
            name='name',
            field=models.CharField(default='Nameless GPS', max_length=100),
        ),
    ]
