# Generated by Django 4.2.2 on 2023-06-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0008_remove_gpsdevice_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='current_altitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='current_speed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
