# Generated by Django 4.2.2 on 2023-06-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0009_gpsdevice_current_altitude_gpsdevice_current_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastlocation',
            name='device_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gps_app.gpsdevice'),
            preserve_default=False,
        ),
    ]
