# Generated by Django 4.2.2 on 2023-06-22 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0010_pastlocation_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
